[package]
name = "mdreader"
version = "0.1.6"
edition = "2021"

[dependencies]
eframe = "0.26.0"
egui = "0.26.0"
walkdir = "2.4.0"
pulldown-cmark = "0.9.3"
sys-locale = "0.3" # For detecting system language
